from flask import Flask, request
import json
from flask_cors import CORS
app = Flask(__name__)

CORS(app)
#keys: name, department, description, url
biosci = {'name': 'Biological Sciences', 'department': 'Biological Sciences', 'description': "Biological Sciences is a multidisciplinary field that \
explores the intricacies of living organisms at various\
 levels, including cells, organisms, and ecosystems. \
 Students delve into cellular and molecular biology, \
 organismal biology, and evolutionary biology, gaining \
 a comprehensive understanding of life's processes. \
 Through hands-on research and practical experiences, \
 they develop critical thinking and problem-solving \
 skills. Graduates can pursue diverse careers in research, \
 healthcare, environmental consulting, biotechnology, \
 or education. Overall, a major in Biological Sciences \
 provides a deep understanding of life and opens doors \
 to a range of rewarding opportunities.", 'url': "https://www.youtube.com/embed/-BJMmUqxD8E"}

genetics = {'name': "Genetics", 'department': 'Biological Sciences', 'description': "Genetics is an exciting and dynamic field of study that focuses on the inheritance, variation, and expression of genes in living organisms. As a major, it delves into the fundamental principles of heredity and genetic mechanisms that underlie the traits and characteristics of organisms. Students explore topics such as DNA structure, gene regulation, genetic mutations, genetic engineering, and genomics. By studying genetics, students gain a profound understanding of how genes influence the development, function, and evolution of organisms. They also learn to apply this knowledge in areas such as medicine, agriculture, biotechnology, and genetic counseling. A major in Genetics provides a solid foundation for a range of careers that involve research, healthcare, genetic engineering, or genetic counseling, contributing to advancements in various fields and improving our understanding of the genetic basis of life.",
            'url': "www.youtube.com/embed/VNqHFyx_uOs"}
neurobio = {'name': 'Neurobiology', 'department': 'Biological Sciences', 
            'description': "Neurobiology is an intriguing and rapidly evolving field of study that focuses on understanding the complex workings of the nervous system. As a major, it encompasses the exploration of the structure, function, and development of the brain and nervous system at various levels, from individual neurons to the entire neural networks. Students delve into topics such as neuroanatomy, neural signaling, synaptic plasticity, sensory and motor systems, cognitive neuroscience, and neuropharmacology. By studying neurobiology, students gain a deep understanding of how the brain processes information, controls behavior, and regulates bodily functions. They also explore the underlying mechanisms of neurological disorders and diseases. This major provides a solid foundation for careers in research, healthcare, neuropharmacology, neuropsychology, or neuroscience-related fields, contributing to advancements in our understanding of the brain and improving treatments for neurological conditions.",
            'url': "https://www.youtube.com/embed/JDhwRctXupk"}
biochem = {'name': 'Biochemistry & Molecular Biology', 'department': 'Biological Sciences', 'description': "Biochemistry and microbiology are two interconnected fields of study that explore the intricate molecular processes within living organisms and the fascinating world of microorganisms. As a major, biochemistry delves into the chemical reactions and molecules that form the basis of life, focusing on topics such as proteins, enzymes, carbohydrates, lipids, and nucleic acids. Microbiology, on the other hand, investigates the structure, function, and diversity of microorganisms, including bacteria, viruses, fungi, and archaea. Students in these majors learn about cellular metabolism, molecular genetics, immunology, microbial ecology, and biotechnology. By studying biochemistry and microbiology, students gain a comprehensive understanding of the complex interactions between molecules and microorganisms. These majors provide a strong foundation for careers in research, pharmaceuticals, healthcare, biotechnology, or environmental science, contributing to advancements in medicine, agriculture, and our understanding of the microbial world.",
           'url':"https://www.youtube.com/embed/X4jEhDLoSdI"}
chem_e = {'name': 'Chemical Engineering', 'department': 'Engineering', 'description': "Chemical Engineering is a diverse and interdisciplinary field of study that combines principles of chemistry, physics, biology, and engineering to design and optimize processes involving chemicals and materials. As a major, it focuses on understanding the properties and transformations of substances on a molecular level, and applying this knowledge to develop and improve industrial processes. Students learn about thermodynamics, reaction kinetics, mass transfer, process design, and process control. They gain skills in problem-solving, data analysis, and using advanced technologies to develop sustainable and efficient solutions for chemical production, energy generation, environmental protection, and more. A major in Chemical Engineering prepares students for careers in industries such as pharmaceuticals, energy, food processing, materials, and environmental engineering, where they play a vital role in creating innovative solutions and contributing to technological advancements.",
          'url': "https://www.youtube.com/embed/YbWq2pOjImg"}
civil_e = {'name': 'Civil Engineering', 'department': 'Engineering', 'description': "Civil Engineering is a crucial field of study that focuses on the design, construction, and maintenance of infrastructure and the built environment. As a major, it encompasses various disciplines such as structural engineering, geotechnical engineering, transportation engineering, and water resources engineering. Students learn how to apply scientific and mathematical principles to design and manage infrastructure projects, including buildings, bridges, roads, dams, and water supply systems. They study topics such as structural analysis, soil mechanics, transportation planning, and environmental engineering. Civil engineering majors gain skills in project management, problem-solving, and utilizing innovative technologies to ensure the safety, sustainability, and efficiency of infrastructure systems. They play a vital role in shaping and improving the physical environment, promoting societal development, and addressing global challenges related to urbanization, transportation, and environmental sustainability.",
           'url': "https://www.youtube.com/embed/Rn4RXNyc2vk"}
elec_e = {'name': 'Electrical Engineering', 'department': 'Engineering', 'description': "Electrical Engineering is a dynamic and highly versatile field of study that focuses on the design, development, and application of electrical and electronic systems. As a major, it covers a broad range of disciplines, including electronics, power systems, telecommunications, control systems, and signal processing. Students learn about the principles of electricity, circuits, and electromagnetic fields, and gain hands-on experience with electronic devices, communication systems, and power distribution networks. Electrical engineering majors acquire skills in analyzing and designing electrical systems, integrating hardware and software components, and optimizing energy efficiency. They play a crucial role in advancing technology and innovation, working in various industries such as telecommunications, renewable energy, robotics, automation, and electronics. Electrical engineering majors contribute to the development of cutting-edge technologies, improve connectivity, and drive progress in fields like healthcare, transportation, and telecommunications.",
          'url': "https://www.youtube.com/embed/yqbOAOR5NQI"}
comp_e = {'name': 'Computer Engineering', 'department': 'Engineering', 'description': "Computer Engineering is an exciting and rapidly evolving field that focuses on the design, development, and integration of computer hardware and software systems. As a major, it combines principles from electrical engineering and computer science to create innovative solutions for a wide range of applications. Students learn about digital systems, computer architecture, programming languages, software engineering, and computer networks. They gain skills in designing and implementing computer hardware, developing software applications, and optimizing system performance. Computer engineering majors play a crucial role in developing cutting-edge technologies, such as embedded systems, artificial intelligence, internet of things (IoT), and cloud computing. They work in various industries, including technology, telecommunications, cybersecurity, and automation, contributing to advancements in computing power, connectivity, and computational efficiency. Computer engineering majors drive innovation, enhance digital experiences, and shape the future of technology.",
          'url': "https://www.youtube.com/embed/wOBk2rbqVps"}
biomed_e = {'name': 'Biomedical Engineering', 'department': 'Engineering', 'description': "Biomedical Engineering is an interdisciplinary field that combines principles of engineering, biology, and medicine to address challenges in healthcare and improve patient care. As a major, it focuses on the development and application of innovative technologies and solutions in the medical and biological fields. Students learn about areas such as medical imaging, biomaterials, biomechanics, tissue engineering, and biomedical instrumentation. They gain skills in designing medical devices, analyzing biological systems, and integrating engineering principles with medical practices. Biomedical engineering majors contribute to advancements in healthcare by developing technologies such as prosthetics, medical imaging systems, implantable devices, and diagnostic tools. They work closely with healthcare professionals to improve patient diagnostics, treatment options, and overall quality of life. Biomedical engineering offers a unique opportunity to combine technical expertise with a passion for healthcare, making a positive impact on people's lives and shaping the future of medicine.",
            'url': "https://www.youtube.com/embed/AWhB6O0tmvw"}
envir_e = {'name': 'Environmental Engineering', 'department': 'Engineering', 'description': "Environmental Engineering is a vital field of study that focuses on the application of engineering principles to address environmental challenges and promote sustainable practices. As a major, it encompasses the design, implementation, and management of solutions to protect and preserve the environment. Students learn about topics such as water and wastewater treatment, air pollution control, solid waste management, environmental impact assessment, and sustainable infrastructure development. Environmental engineering majors gain skills in analyzing and mitigating environmental risks, developing sustainable technologies, and implementing strategies for resource conservation and pollution prevention. They play a critical role in addressing pressing environmental issues, such as climate change, water scarcity, and pollution. Environmental engineering majors work in industries such as consulting firms, government agencies, and research institutions, contributing to the development of eco-friendly practices, renewable energy systems, and sustainable infrastructure projects. They strive to create a greener and healthier future by ensuring the protection and preservation of our natural resources and ecosystems.",
           'url': "https://www.youtube.com/embed/JnMNzN74QGQ"}
materials_e = {'name': 'Materials Science Engineering', 'department': 'Engineering', 'description': "Materials Science Engineering is a fascinating and interdisciplinary field that explores the properties, structure, and applications of materials. As a major, it combines principles from physics, chemistry, and engineering to understand and manipulate the behavior of materials at the atomic and molecular level. Students learn about topics such as materials synthesis, characterization techniques, material properties, and material processing. Materials science engineering majors gain skills in designing and developing new materials with enhanced properties, such as strength, durability, conductivity, and optical properties. They play a crucial role in various industries, including aerospace, electronics, energy, healthcare, and automotive, by advancing materials technology and developing innovative solutions. Whether it's designing lightweight alloys for aircraft, developing new electronic devices, or creating advanced biomaterials for medical applications, materials science engineering majors contribute to technological advancements and shape the future of materials and their applications.",
               'url': "https://www.youtube.com/embed/omiTt_73LuA"}
mech_e = {'name': 'Mechanical Engineering', 'department': 'Engineering', 'description': "Mechanical Engineering is a diverse and dynamic field of study that focuses on the design, analysis, and manufacturing of mechanical systems and devices. As a major, it covers a wide range of disciplines, including mechanics, thermodynamics, materials science, robotics, and fluid dynamics. Students learn to apply principles of physics and engineering to create innovative solutions for a variety of industries. Mechanical engineering majors gain skills in designing and optimizing mechanical systems, conducting simulations and analysis, and utilizing advanced technologies and tools. They play a crucial role in fields such as automotive, aerospace, energy, manufacturing, and robotics, contributing to the development of efficient engines, sustainable energy systems, advanced machinery, and automation solutions. Mechanical engineering majors have opportunities to work on diverse projects, from designing cutting-edge vehicles to creating renewable energy technologies, making a significant impact on industry, technology, and society as a whole.",
          'url': "https://www.youtube.com/embed/W0W1kh-BrKM"}
cs = {'name': 'Computer Science', 'department': 'Information & Computer Science', 'description': "Computer Science is a dynamic and rapidly evolving field of study that focuses on the theory, design, and development of computer systems and software. As a major, it encompasses a broad range of topics, including algorithms, programming languages, data structures, artificial intelligence, and computer networks. Students learn problem-solving skills, programming languages, and software development methodologies. Computer science majors gain expertise in areas such as software engineering, data analysis, cybersecurity, and machine learning. They play a vital role in developing innovative technologies, creating software applications, and advancing fields like artificial intelligence and data science. Computer science majors find opportunities in industries such as technology, finance, healthcare, gaming, and cybersecurity, contributing to advancements in computing and shaping the future of technology-driven society.",
      'url': "https://www.youtube.com/embed/fHvf7J6xuH0"}
data = {'name': 'Data Science', 'department': 'Information & Computer Science', 'description': "Data Science is an interdisciplinary field that combines elements of mathematics, statistics, and computer science to extract knowledge and insights from complex and large datasets. As a major, it encompasses a wide range of skills and techniques, including data analysis, machine learning, data visualization, and data mining. Students learn to collect, clean, and preprocess data, apply statistical models and algorithms, and communicate findings effectively. Data science majors gain proficiency in programming languages and tools used for data manipulation and analysis. They play a critical role in various industries, such as finance, healthcare, marketing, and technology, by using data-driven approaches to solve complex problems, make data-informed decisions, and uncover patterns and trends. With the growing importance of data in today's world, data science majors are in high demand and have numerous opportunities for impactful and rewarding careers.",
        'url': "https://www.youtube.com/embed/hREfleo04GE"}
game = {'name': 'Game Design & Interactive Media', 'department': 'Information & Computer Science', 'description': "Game Design and Interactive Media is an exciting and innovative field of study that focuses on the creation, development, and design of interactive experiences, including video games, virtual reality, augmented reality, and other digital media platforms. As a major, it combines elements of art, computer science, storytelling, and user experience design. Students learn about game mechanics, character development, level design, game programming, and interactive storytelling. They gain skills in designing engaging and immersive experiences, utilizing cutting-edge technologies, and understanding user behaviors and preferences. Game design and interactive media majors play a vital role in the entertainment industry, digital marketing, education, and simulation industries by creating captivating and meaningful interactive experiences. They contribute to the development of innovative games, virtual worlds, and interactive media applications that entertain, educate, and engage audiences in unique and interactive ways.",
        'url': "https://www.youtube.com/embed/NnUoQ2VdDog"}
inf = {'name': 'Informatics', 'department': 'Information & Computer Science', 'description': "Informatics, also known as Information Science or Information Systems, is a multidisciplinary field of study that focuses on the effective use of information and technology in various domains. As a major, it combines elements of computer science, data analysis, human-computer interaction, and organizational behavior. Students learn about information management, database systems, data analytics, user experience design, and information security. Informatics majors gain skills in collecting, organizing, analyzing, and interpreting information to address complex problems and make informed decisions. They play a crucial role in industries such as healthcare, finance, e-commerce, and government, where they contribute to the design and development of information systems, improve data-driven decision-making processes, and enhance user experiences. Informatics majors bridge the gap between technology and people, applying their knowledge to leverage information effectively and shape the future of information-driven society.",
       'url': "https://www.youtube.com/embed/13DkIfw6K-E"}
swe = {'name': 'Software Engineering', 'department': 'Information & Computer Science', 'description': "Software Engineering is a discipline within computer science that focuses on the design, development, and maintenance of reliable and efficient software systems. As a major, it combines principles of computer science, mathematics, and engineering to create robust and scalable software solutions. Students learn about software development methodologies, programming languages, software testing, software architecture, and project management. Software engineering majors gain skills in designing software systems, writing clean and maintainable code, collaborating in teams, and ensuring software quality. They play a crucial role in various industries, including technology, finance, healthcare, and entertainment, by developing innovative software applications, optimizing performance, and improving user experiences. Software engineering majors contribute to the advancement of technology by creating efficient and reliable software systems that address complex problems and enhance productivity.",
       'url': "https://www.youtube.com/embed/ZvZhgF8Hk2U"}
ics = {'name': 'Information & Computer Science', 'department': 'Information & Computer Science', 'description': "Information and Computer Science is an interdisciplinary field of study that combines elements of computer science, information science, and technology to explore the complexities of information processing, storage, and retrieval. As a major, it encompasses a wide range of subjects, including programming, algorithms, data structures, databases, network systems, and human-computer interaction. Students learn to develop software applications, analyze and manage data, design information systems, and understand the impact of technology on society. Information and computer science majors gain critical problem-solving skills, programming proficiency, and an understanding of how information is organized, accessed, and utilized. They play a crucial role in industries such as technology, finance, healthcare, and entertainment, where they contribute to the development of innovative software solutions, data-driven insights, and secure information systems. Information and computer science majors are at the forefront of technological advancements, shaping the digital landscape and driving progress in the modern world.",
       'url': "https://www.youtube.com/embed/fHvf7J6xuH0"}

phys = {'name': 'Physics', 'department': 'Physical Sciences', 'description': "Physics is a fundamental and far-reaching field of study that explores the fundamental principles governing the behavior of matter and energy. As a major, it covers a wide range of topics, including classical mechanics, quantum mechanics, electromagnetism, thermodynamics, and astrophysics. Students delve into understanding the laws and principles that govern the universe, ranging from the smallest particles to the vastness of space. Physics majors learn mathematical modeling, experimental techniques, and data analysis to study natural phenomena and develop theories to explain them. They gain skills in problem-solving, critical thinking, and quantitative analysis. Physics majors contribute to advancements in fields such as technology, energy, medicine, and astronomy. They pursue careers in research, academia, engineering, and other industries where their analytical skills and scientific expertise are highly valued. Physics majors have the opportunity to unravel the mysteries of the universe, expand human knowledge, and drive innovation and technological progress.",
        'url': "https://www.youtube.com/embed/PW0nr42J-1A"}
chem = {'name': 'Chemistry', 'department': 'Physical Sciences', 'description': "Chemistry is a fundamental field of study that explores the composition, properties, and transformations of matter at the atomic and molecular level. As a major, it encompasses a wide range of disciplines, including organic chemistry, inorganic chemistry, physical chemistry, and analytical chemistry. Students learn about chemical reactions, molecular structures, spectroscopy, and laboratory techniques. Chemistry majors gain skills in conducting experiments, analyzing data, and synthesizing compounds. They play a crucial role in various industries, such as pharmaceuticals, materials, energy, and environmental sciences, by developing new substances, conducting research, and solving complex problems. Chemistry majors contribute to advancements in areas such as drug discovery, materials development, environmental remediation, and sustainable technologies. They pursue careers in research, academia, chemical engineering, and quality control, where their scientific expertise and analytical skills are highly valued. Chemistry majors drive innovation, contribute to scientific discoveries, and improve our understanding of the world around us.",
        'url': "https://www.youtube.com/embed/MbOfQFnw_7I"}
math = {'name': 'Mathematics', 'department': 'Physical Sciences', 'description': "Mathematics is a foundational and versatile field of study that explores the properties, relationships, and patterns of numbers, quantities, and abstract structures. As a major, it encompasses various branches, including pure mathematics, applied mathematics, and mathematical statistics. Students delve into topics such as calculus, algebra, geometry, logic, and probability theory. Mathematics majors develop strong analytical and problem-solving skills, as well as a deep understanding of mathematical principles and concepts. They apply mathematical techniques to solve complex problems in fields such as physics, engineering, economics, computer science, and cryptography. Mathematics majors pursue careers in research, academia, finance, data analysis, and technology, where their quantitative skills and logical reasoning are highly valued. They play a vital role in developing mathematical models, analyzing data, and making informed decisions based on rigorous mathematical principles. Mathematics majors contribute to advancements in various disciplines, drive innovation, and expand our understanding of the underlying structure of the universe.",
        'url': "https://www.youtube.com/embed/vASmRBED3uM"}
ess = {'name': 'Earth Systems Science', 'department': 'Physical Sciences', 'description': "Earth System Science is an interdisciplinary field of study that examines the complex interactions between the Earth's atmosphere, hydrosphere, biosphere, and geosphere. As a major, it integrates elements of geology, atmospheric science, oceanography, and ecology to understand Earth's processes and how they shape the planet's climate, ecosystems, and natural resources. Students explore topics such as climate change, natural hazards, water resources, biogeochemical cycles, and Earth's geological history. Earth System Science majors gain a holistic understanding of Earth's interconnected systems and develop skills in data analysis, modeling, fieldwork, and scientific research. They play a vital role in addressing environmental challenges, such as sustainable resource management, conservation, and climate resilience. Earth System Science majors contribute to a better understanding of the Earth's dynamics, helping society make informed decisions to preserve and protect our planet for future generations.",
       'url': "https://www.youtube.com/embed/l0NrDpiDC20"}


major = {'biosci': biosci, 'genetics': genetics, 'neurobio': neurobio, 'biochem': biochem,
          'chemE': chem_e, 'civilE': civil_e, 'elecE': elec_e, 'compE': comp_e, 'biomed': biomed_e,
          'envirE': envir_e, 'materials': materials_e, 'mechE': mech_e,
          'cs': cs, 'data': data, 'game': game, 'inf': inf, 'swe': swe, 'ics': ics,
          'physics': phys, 'chem': chem, 'math': math, 'earth': ess}


@app.route('/major/<major_input>')
def majors(major_input):
    args = request.args["major"] 
    major_input = args.get('major')
    desc = json.dumps(major[major_input])
    return desc



if __name__ == "__main__":
    app.run(debug=True, port=8000)